/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Contacto extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /** Creates new form Contacto */
    public Contacto(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelNumeroFijo = new javax.swing.JLabel();
        jLabelEstrato = new javax.swing.JLabel();
        jLabelTipoVivienda = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jComboBoxEstrato = new javax.swing.JComboBox<>();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jComboBoxTipoVivienda = new javax.swing.JComboBox<>();
        jComboBoxLocalidad = new javax.swing.JComboBox<>();
        jTextFieldNumeroFijo = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("UBICACION Y CONTACTO");

        jLabelLocalidad.setText("Localidad");

        jLabelDireccion.setText("Direccion");

        jLabelNumeroFijo.setText("Numero Fijo");

        jLabelEstrato.setText("Estrato");

        jLabelTipoVivienda.setText("Tipo de vivienda");

        jLabelCelular.setText("Celular");

        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabelNumeroFijo)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNumeroFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelLocalidad)
                        .addGap(29, 29, 29)
                        .addComponent(jComboBoxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelTipoVivienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelCelular)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguienteModificar)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEstrato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDireccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelEstrato)
                            .addComponent(jComboBoxEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLocalidad)
                            .addComponent(jLabelTipoVivienda)
                            .addComponent(jComboBoxTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroFijo)
                            .addComponent(jTextFieldNumeroFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular))
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSiguienteModificar)
                            .addComponent(jButtonVolver))
                        .addGap(48, 48, 48))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstrato;
    private javax.swing.JComboBox<String> jComboBoxLocalidad;
    private javax.swing.JComboBox<String> jComboBoxTipoVivienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEstrato;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelNumeroFijo;
    private javax.swing.JLabel jLabelTipoVivienda;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNumeroFijo;
    // End of variables declaration//GEN-END:variables

    private void CargarComboBox() {
        String estrato[] = { "","0","1","2","3","4","5","6"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(estrato);
        jComboBoxEstrato.setModel(model);
        String vivienda[] = { "","Propia","Arrendada","Familiar"};
        final DefaultComboBoxModel model1 = new DefaultComboBoxModel(vivienda);
        jComboBoxTipoVivienda.setModel(model1);
        String localidades[] = { "","no aplica","1 Usaquén","2 Chapinero","3 Santa Fe",
        "4 San Cristóbal","5 Usme","6 Tunjuelito","7 Bosa","8 Kennedy",
        "9 Fontibón","10 Engativá","11 Suba","12 Barrios Unidos","13 Teusaquillo",
        "14 Los Mártires","15 Antonio Nariño","16 Puente Aranda","17 La Candelaria",
        "18 Rafael Uribe Uribe","19 Ciudad Bolívar","20 Sumapaz"};
        final DefaultComboBoxModel model2 = new DefaultComboBoxModel(localidades);
        jComboBoxLocalidad.setModel(model2);
    }
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                if(VerificarTelefonos()){
                    String direccion=jTextFieldDireccion.getText();
                    int estrato=Integer.parseInt((String) jComboBoxEstrato.getSelectedItem());
                    String localidad=(String) jComboBoxLocalidad.getSelectedItem();
                    String tipoVivienda=(String) jComboBoxTipoVivienda.getSelectedItem();
                    long fijo=-1;
                    if(!(jTextFieldNumeroFijo.getText().equals(""))){
                        fijo=Long.parseLong(jTextFieldNumeroFijo.getText());
                    }
                    long celular=-1;
                    if(!(jTextFieldCelular.getText().equals(""))){
                        celular=Long.parseLong(jTextFieldCelular.getText());
                    }
                    if(principal.CrearContacto(cedula,direccion,estrato,localidad,tipoVivienda,fijo,celular)){
                        principal.mostrarPanelPerfilAcademico();
                        principal.CambioPerfilAcademico(1);
                        principal.CambioCedulaPerfilAcademico(cedula);
                    }else{
                       JOptionPane.showMessageDialog(this, "DATOS ERRONEOS"); 
                    }
                }    
            }
        }if(panel==2){
            
        }
    }

    private void cambiarVolver() {
        if(panel==1){
            principal.mostrarPanelDatosPersonales();
            principal.CambioDatosPersonales(1);
            principal.CambioCedulaDatosPersonales(cedula);
            principal.CargarAlumno(cedula);
        }if(panel==2){
            principal.mostrarPanelModificar();
        }
    }

    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }

    private boolean VerificarDatos() {
        if(jTextFieldDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA DIRECCION");
            return false;
        }else if(((String) jComboBoxEstrato.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE EL ESTRATO");
            return false;
        }else if(((String) jComboBoxLocalidad.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE LA LOCALIDAD");
            return false;
        }else if(((String) jComboBoxTipoVivienda.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE EL TIPO DE VIVIENDA");
            return false;
        }
        return true;
    }

    private boolean VerificarTelefonos() {
        if(!(jTextFieldCelular.getText().equals("")&&jTextFieldNumeroFijo.getText().equals(""))){
            if(jTextFieldCelular.getText().equals("")){
                if(esNumero(jTextFieldNumeroFijo.getText())){
                    JOptionPane.showMessageDialog(null, "NUMERO FIJO ERRONEO");
                    return false;
                }
            }else if(jTextFieldNumeroFijo.getText().equals("")){
                if(esNumero(jTextFieldCelular.getText())){
                    JOptionPane.showMessageDialog(null, "NUMERO CELULAR ERRONEO");
                    return false;
                }
            }else{
                if(esNumero(jTextFieldCelular.getText())){
                    JOptionPane.showMessageDialog(null, "NUMERO CELULAR ERRONEO");
                    return false;
                }
                if(esNumero(jTextFieldNumeroFijo.getText())){
                    JOptionPane.showMessageDialog(null, "NUMERO FIJO ERRONEO");
                    return false;
                }
            }
        }
        return true;    
    }
    private static boolean esNumero(String cadena) {
        try {
            Long.parseLong(cadena);
            return false;
        } catch (NumberFormatException nfe) {
            return true;
        }
    }
    void CargarContacto(String[] DatosContacto) {
        jTextFieldDireccion.setText(DatosContacto[0]);
        jComboBoxLocalidad.setSelectedIndex(TipoLocalidad(DatosContacto[1]));
        jComboBoxEstrato.setSelectedIndex((Integer.parseInt(DatosContacto[2]))+1);;
        if(!(DatosContacto[3].equals("-1"))){
            jTextFieldNumeroFijo.setText(DatosContacto[3]);
        }else{
            jTextFieldNumeroFijo.setText("");
        }
        if(!(DatosContacto[4].equals("-1"))){
            jTextFieldCelular.setText(DatosContacto[4]);
        }else{
            jTextFieldCelular.setText("");
        }
        jComboBoxTipoVivienda.setSelectedIndex(TipoVivienda(DatosContacto[5]));
        principal.EliminarContacto(cedula);
    }

    private int TipoLocalidad(String localidad) {
        if(localidad.equals("no aplica")){
            return 1;
        }else if(localidad.equals("1 Usaquén")){
            return 2;
        }else if(localidad.equals("2 Chapinero")){
            return 3;
        }else if(localidad.equals("3 Santa Fe")){
            return 4;
        }else if(localidad.equals("4 San Cristóbal")){
            return 5;
        }else if(localidad.equals("5 Usme")){
            return 6;
        }else if(localidad.equals("6 Tunjuelito")){
            return 7;
        }else if(localidad.equals("7 Bosa")){
            return 8;
        }else if(localidad.equals("8 Kennedy")){
            return 9;
        }else if(localidad.equals("9 Fontibón")){
            return 10;
        }else if(localidad.equals("10 Engativá")){
            return 11;
        }else if(localidad.equals("11 Suba")){
            return 12;
        }else if(localidad.equals("12 Barrios Unidos")){
            return 13;
        }else if(localidad.equals("13 Teusaquillo")){
            return 14;
        }else if(localidad.equals("14 Los Mártires")){
            return 15;
        }else if(localidad.equals("15 Antonio Nariño")){
            return 16;
        }else if(localidad.equals("16 Puente Aranda")){
            return 17;
        }else if(localidad.equals("17 La Candelaria")){
            return 18;
        }else if(localidad.equals("18 Rafael Uribe Uribe")){
            return 19;
        }else if(localidad.equals("19 Ciudad Bolívar")){
            return 20;
        }else if(localidad.equals("20 Sumapaz")){
            return 21;
        }
        return 0;
    }

    private int TipoVivienda(String vivienda) {
        if(vivienda.equals("Propia")){
            return 1;
        }else if(vivienda.equals("Arrendada")){
            return 2;
        }else if(vivienda.equals("Familiar")){
            return 2;
        }
        return 0;
    }
}
