/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class DatosPersonales extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /**
     * Creates new form DatosPersonales
     */
    public DatosPersonales(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosPersonales = new javax.swing.JLabel();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelOcupacion = new javax.swing.JLabel();
        jLabelTipoIdentificacion = new javax.swing.JLabel();
        jLabelLugarNacimiento = new javax.swing.JLabel();
        jLabelTallaPantalon = new javax.swing.JLabel();
        jLabelTallaZapatos = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldOcupacion = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldTallaPantalon = new javax.swing.JTextField();
        jTextFieldTallaZapatos = new javax.swing.JTextField();
        jTextFieldLugarNacimiento = new javax.swing.JTextField();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jComboBoxTipoIdentificacion = new javax.swing.JComboBox<>();
        jLabelTallaCamisa = new javax.swing.JLabel();
        jTextFieldTallaCamisa = new javax.swing.JTextField();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDatosPersonales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDatosPersonales.setText("DATOS PERSONALES");
        add(jLabelDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 0, -1, -1));

        jLabelIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIdentificacion.setText("Indentificación");
        add(jLabelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 121, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellidos");
        add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 59, -1, -1));

        jLabelFechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaNacimiento.setText("Fecha Nacimiento");
        add(jLabelFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 179, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombres");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 65, -1, -1));

        jLabelOcupacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOcupacion.setText("Ocupación");
        add(jLabelOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 237, -1, -1));

        jLabelTipoIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTipoIdentificacion.setText("Tipo de Documento");
        add(jLabelTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 121, -1, -1));

        jLabelLugarNacimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLugarNacimiento.setText("Lugar Nacimiento");
        add(jLabelLugarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 179, -1, -1));

        jLabelTallaPantalon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTallaPantalon.setText("Talla Pantalon");
        add(jLabelTallaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 292, -1, -1));

        jLabelTallaZapatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTallaZapatos.setText("Talla Zapatos ");
        add(jLabelTallaZapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 341, -1, -1));

        jTextFieldIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 115, 190, 28));

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 59, 190, 28));

        jTextFieldOcupacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 231, 190, 28));

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 59, 191, 28));

        jTextFieldTallaPantalon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldTallaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 286, 190, 28));

        jTextFieldTallaZapatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldTallaZapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 341, 190, 28));

        jTextFieldLugarNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldLugarNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 173, 190, 28));

        jButtonSiguienteModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });
        add(jButtonSiguienteModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 396, -1, -1));

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 396, -1, -1));

        jComboBoxTipoIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jComboBoxTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 115, 190, 28));

        jLabelTallaCamisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTallaCamisa.setText("Talla Camisa ");
        add(jLabelTallaCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 292, -1, -1));

        jTextFieldTallaCamisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldTallaCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 286, 190, 28));

        jDateChooserFechaNacimiento.setDateFormatString("yyyy/MM/dd");
        add(jDateChooserFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 173, 190, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxTipoIdentificacion;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelLugarNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOcupacion;
    private javax.swing.JLabel jLabelTallaCamisa;
    private javax.swing.JLabel jLabelTallaPantalon;
    private javax.swing.JLabel jLabelTallaZapatos;
    private javax.swing.JLabel jLabelTipoIdentificacion;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldLugarNacimiento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldOcupacion;
    private javax.swing.JTextField jTextFieldTallaCamisa;
    private javax.swing.JTextField jTextFieldTallaPantalon;
    private javax.swing.JTextField jTextFieldTallaZapatos;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }

    private void CargarComboBox() {
        String labels[] = { "","Targeta identificacion","Cedula ciudadania"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(labels);
        jComboBoxTipoIdentificacion.setModel(model);
        jDateChooserFechaNacimiento.getDateEditor().setEnabled(false);
    }

    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                if(AlumnoExiste()){
                    if(tamanioCadena()){
                        long identificacion = Long.parseLong(jTextFieldIdentificacion.getText());
                        String tipoIdentificacion = (String) jComboBoxTipoIdentificacion.getSelectedItem();
                        String nombre = jTextFieldNombre.getText();
                        String apellido = jTextFieldApellido.getText();
                        String fechaNacimiento =((JTextField)jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
                        String lugarNacimiento = jTextFieldLugarNacimiento.getText();
                        String ocupacion = jTextFieldOcupacion.getText();
                        String tallaZapatos = jTextFieldTallaZapatos.getText();
                        String tallaPantalon = jTextFieldTallaPantalon.getText();
                        String tallaCamisa = jTextFieldTallaCamisa.getText();
                        if(principal.CrearAlumno(identificacion,tipoIdentificacion,nombre,apellido,fechaNacimiento,lugarNacimiento,ocupacion,tallaZapatos,tallaPantalon,tallaCamisa)){
                            principal.mostrarPanelContacto();
                            principal.CambioContacto(1);
                            cedula = Long.parseLong(jTextFieldIdentificacion.getText());
                            principal.CambioCedulaContacto(cedula);
                        }else{
                            JOptionPane.showMessageDialog(this, "Datos erroenos");
                        }
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "ALUMNO YA EXISTENTE");
                }
            }   
        }if(panel==2){
            if(VerificarDatos()){
                if(AlumnoExisteSin()){
                    if(tamanioCadena()){
                        long identificacion = Long.parseLong(jTextFieldIdentificacion.getText());
                        String tipoIdentificacion = (String) jComboBoxTipoIdentificacion.getSelectedItem();
                        String nombre = jTextFieldNombre.getText();
                        String apellido = jTextFieldApellido.getText();
                        String fechaNacimiento =((JTextField)jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
                        String lugarNacimiento = jTextFieldLugarNacimiento.getText();
                        String ocupacion = jTextFieldOcupacion.getText();
                        String tallaZapatos = jTextFieldTallaZapatos.getText();
                        String tallaPantalon = jTextFieldTallaPantalon.getText();
                        String tallaCamisa = jTextFieldTallaCamisa.getText();
                        if(principal.ModificarAlumno(identificacion,tipoIdentificacion,nombre,apellido,fechaNacimiento,lugarNacimiento,ocupacion,tallaZapatos,tallaPantalon,tallaCamisa,cedula)){
                            principal.mostrarPanelModificar();
                            principal.CargarAlumnos();
                        }else{
                            JOptionPane.showMessageDialog(this, "Datos erroenos");
                        }
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "ALUMNO YA EXISTENTE");
                }
            }
        }
    }

    private boolean VerificarDatos() {
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE");
            return false;
        }else if(jTextFieldApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL APELLIDO");
            return false;
        }else if(((String) jComboBoxTipoIdentificacion.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE EL TIPO DE DOCUMENTO");
            return false;
        }else if(esNumero(jTextFieldIdentificacion.getText())){
            JOptionPane.showMessageDialog(null, "DOCUMENTO ERRONEO");
            return false;
        }else if((((JTextField)jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText()).equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA FECHA DE NACIMIENTO");
            return false;
        }
        return true;
    }
    private boolean AlumnoExiste() {
        return principal.AlumnoExiste(Long.parseLong(jTextFieldIdentificacion.getText()));
    }
    private boolean AlumnoExisteSin() {
        return principal.AlumnoExisteSin(Long.parseLong(jTextFieldIdentificacion.getText()),cedula);
    }
    private static boolean esNumero(String cadena) {
        try {
            Long.parseLong(cadena);
            return false;
        } catch (NumberFormatException nfe) {
            return true;
        }
    }

    private void cambiarVolver() {
        if(panel==1){
            
            if(cedula==0){
                principal.mostrarPanelHome();
            }else{
                principal.mostrarPanelHome();
                principal.EliminarAlumno(cedula);
                cedula=0;
            }
        }if(panel==2){
            principal.mostrarPanelModificar();
            principal.CargarAlumnos();
        }
    }

    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }

    void CargarAlumno(String[] DatosAlumno) {
        jTextFieldIdentificacion.setText(DatosAlumno[0]);
        jComboBoxTipoIdentificacion.setSelectedIndex(TipoIdentificacion(DatosAlumno[1]));
        jTextFieldNombre.setText(DatosAlumno[2]);
        jTextFieldApellido.setText(DatosAlumno[3]);
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = null;
        try {
            date = formatter.parse(DatosAlumno[4]);
        } catch (ParseException ex) {
            Logger.getLogger(DatosPersonales.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooserFechaNacimiento.setDate(date);
        jTextFieldLugarNacimiento.setText(DatosAlumno[5]);
        jTextFieldOcupacion.setText(DatosAlumno[6]);
        jTextFieldTallaPantalon.setText(DatosAlumno[7]);
        jTextFieldTallaZapatos.setText(DatosAlumno[8]);
        jTextFieldTallaCamisa.setText(DatosAlumno[9]);
        principal.EliminarAlumno(cedula);
    }
    void CargarAlumnoModificar(String[] DatosAlumno) {
        jTextFieldIdentificacion.setText(DatosAlumno[0]);
        jComboBoxTipoIdentificacion.setSelectedIndex(TipoIdentificacion(DatosAlumno[1]));
        jTextFieldNombre.setText(DatosAlumno[2]);
        jTextFieldApellido.setText(DatosAlumno[3]);
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = null;
        try {
            date = formatter.parse(DatosAlumno[4]);
        } catch (ParseException ex) {
            Logger.getLogger(DatosPersonales.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooserFechaNacimiento.setDate(date);
        jTextFieldLugarNacimiento.setText(DatosAlumno[5]);
        jTextFieldOcupacion.setText(DatosAlumno[6]);
        jTextFieldTallaPantalon.setText(DatosAlumno[7]);
        jTextFieldTallaZapatos.setText(DatosAlumno[8]);
        jTextFieldTallaCamisa.setText(DatosAlumno[9]);
    }

    private int TipoIdentificacion(String TipoIdentificacion) {
        if(TipoIdentificacion.equals("Targeta identificacion")){
            return 1;
        }else if(TipoIdentificacion.equals("Cedula ciudadania")){
            return 2;
        }
        return 0;
    }

    private boolean tamanioCadena() {
        if(((jTextFieldNombre.getText()).length())>25){
            JOptionPane.showMessageDialog(null, "NOMBRE EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldApellido.getText()).length())>25){
            JOptionPane.showMessageDialog(null, "APELLIDO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldIdentificacion.getText()).length())>15){
            JOptionPane.showMessageDialog(null, "IDENTIFICACION EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldLugarNacimiento.getText()).length())>20){
            JOptionPane.showMessageDialog(null, "LUGAR NACIMIENTO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldOcupacion.getText()).length())>20){
            JOptionPane.showMessageDialog(null, "OCUPACION EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldTallaPantalon.getText()).length())>8){
            JOptionPane.showMessageDialog(null, "TALLA PANTALON EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldTallaCamisa.getText()).length())>8){
            JOptionPane.showMessageDialog(null, "TALLA CAMISA EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldTallaZapatos.getText()).length())>8){
            JOptionPane.showMessageDialog(null, "TALLA ZAPATOS EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }
}

