/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author david
 */
public class DatosPersonales extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /**
     * Creates new form DatosPersonales
     */
    public DatosPersonales(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosPersonales = new javax.swing.JLabel();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelOcupacion = new javax.swing.JLabel();
        jLabelTipoIdentificacion = new javax.swing.JLabel();
        jLabelLugarNacimiento = new javax.swing.JLabel();
        jLabelTallaPantalon = new javax.swing.JLabel();
        jLabelTallaZapatos = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldOcupacion = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldTallaPantalon = new javax.swing.JTextField();
        jTextFieldTallaZapatos = new javax.swing.JTextField();
        jTextFieldLugarNacimiento = new javax.swing.JTextField();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jComboBoxTipoIdentificacion = new javax.swing.JComboBox<>();
        jLabelTallaCamisa = new javax.swing.JLabel();
        jTextFieldTallaCamisa = new javax.swing.JTextField();
        jDateChooserFechaNacimiento = new com.toedter.calendar.JDateChooser();

        jLabelDatosPersonales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDatosPersonales.setText("DATOS PERSONALES");

        jLabelIdentificacion.setText("Identifiacion");

        jLabelApellido.setText("Apellido");

        jLabelFechaNacimiento.setText("Fecha Nacimiento");

        jLabelNombre.setText("Nombre");

        jLabelOcupacion.setText("Ocupacion");

        jLabelTipoIdentificacion.setText("TipoIdentificacion");

        jLabelLugarNacimiento.setText("Lugar Nacimiento");

        jLabelTallaPantalon.setText("Talla Pantalon");

        jLabelTallaZapatos.setText("Talla Zapatos ");

        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelTallaCamisa.setText("Talla Camisa ");

        jDateChooserFechaNacimiento.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdentificacion)
                        .addGap(55, 55, 55)
                        .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTipoIdentificacion)
                            .addComponent(jLabelFechaNacimiento)
                            .addComponent(jLabelTallaPantalon)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOcupacion)
                                .addGap(14, 14, 14)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipoIdentificacion, 0, 117, Short.MAX_VALUE)
                            .addComponent(jTextFieldOcupacion)
                            .addComponent(jTextFieldTallaPantalon)
                            .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelApellido)
                            .addComponent(jLabelNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTallaCamisa)
                            .addComponent(jLabelTallaZapatos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelLugarNacimiento)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTallaZapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTallaCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDatosPersonales)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(218, 218, 218)
                        .addComponent(jButtonSiguienteModificar)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDatosPersonales)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentificacion)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoIdentificacion)
                        .addComponent(jComboBoxTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelApellido)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaNacimiento)
                            .addComponent(jLabelLugarNacimiento)
                            .addComponent(jTextFieldLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTallaPantalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTallaPantalon)
                            .addComponent(jLabelTallaCamisa)
                            .addComponent(jTextFieldTallaCamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSiguienteModificar)
                            .addComponent(jButtonVolver))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooserFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOcupacion)
                            .addComponent(jTextFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTallaZapatos)
                            .addComponent(jTextFieldTallaZapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxTipoIdentificacion;
    private com.toedter.calendar.JDateChooser jDateChooserFechaNacimiento;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelFechaNacimiento;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelLugarNacimiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOcupacion;
    private javax.swing.JLabel jLabelTallaCamisa;
    private javax.swing.JLabel jLabelTallaPantalon;
    private javax.swing.JLabel jLabelTallaZapatos;
    private javax.swing.JLabel jLabelTipoIdentificacion;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldLugarNacimiento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldOcupacion;
    private javax.swing.JTextField jTextFieldTallaCamisa;
    private javax.swing.JTextField jTextFieldTallaPantalon;
    private javax.swing.JTextField jTextFieldTallaZapatos;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }

    private void CargarComboBox() {
        String labels[] = { "","Targeta identificacion","Cedula ciudadania"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(labels);
        jComboBoxTipoIdentificacion.setModel(model);
        jDateChooserFechaNacimiento.getDateEditor().setEnabled(false);
    }

    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                if(AlumnoExiste()){
                    long identificacion = Long.parseLong(jTextFieldIdentificacion.getText());
                    String tipoIdentificacion = (String) jComboBoxTipoIdentificacion.getSelectedItem();
                    String nombre = jTextFieldNombre.getText();
                    String apellido = jTextFieldApellido.getText();
                    String fechaNacimiento =((JTextField)jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText();
                    String lugarNacimiento = jTextFieldLugarNacimiento.getText();
                    String ocupacion = jTextFieldOcupacion.getText();
                    String tallaZapatos = jTextFieldTallaZapatos.getText();
                    String tallaPantalon = jTextFieldTallaPantalon.getText();
                    String tallaCamisa = jTextFieldTallaCamisa.getText();
                    if(principal.CrearAlumno(identificacion,tipoIdentificacion,nombre,apellido,fechaNacimiento,lugarNacimiento,ocupacion,tallaZapatos,tallaPantalon,tallaCamisa)){
                        principal.mostrarPanelContacto();
                        principal.CambioContacto(1);
                        cedula = Long.parseLong(jTextFieldIdentificacion.getText());
                        principal.CambioCedulaContacto(cedula);
                    }else{
                        JOptionPane.showMessageDialog(this, "Datos erroenos");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "ALUMNO YA EXISTENTE");
                }
            }   
        }if(panel==2){
            
        }
    }

    private boolean VerificarDatos() {
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE");
            return false;
        }else if(jTextFieldApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL APELLIDO");
            return false;
        }else if(((String) jComboBoxTipoIdentificacion.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE EL TIPO DE DOCUMENTO");
            return false;
        }else if(esNumero(jTextFieldIdentificacion.getText())){
            JOptionPane.showMessageDialog(null, "DOCUMENTO ERRONEO");
            return false;
        }else if((((JTextField)jDateChooserFechaNacimiento.getDateEditor().getUiComponent()).getText()).equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA FECHA DE NACIMIENTO");
            return false;
        }
        return true;
    }
    private boolean AlumnoExiste() {
        return principal.AlumnoExiste(Long.parseLong(jTextFieldIdentificacion.getText()));
    }
    private static boolean esNumero(String cadena) {
        try {
            Long.parseLong(cadena);
            return false;
        } catch (NumberFormatException nfe) {
            return true;
        }
    }

    private void cambiarVolver() {
        if(panel==1){
            
            if(cedula==0){
                principal.mostrarPanelHome();
            }else{
                principal.mostrarPanelHome();
                principal.EliminarAlumno(cedula);
                cedula=0;
            }
        }if(panel==2){
            principal.mostrarPanelModificar();
        }
    }

    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }

    void CargarAlumno(String[] DatosAlumno) {
        jTextFieldIdentificacion.setText(DatosAlumno[0]);
        jComboBoxTipoIdentificacion.setSelectedIndex(TipoIdentificacion(DatosAlumno[1]));
        jTextFieldNombre.setText(DatosAlumno[2]);
        jTextFieldApellido.setText(DatosAlumno[3]);
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = null;
        try {
            date = formatter.parse(DatosAlumno[4]);
        } catch (ParseException ex) {
            Logger.getLogger(DatosPersonales.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooserFechaNacimiento.setDate(date);
        jTextFieldLugarNacimiento.setText(DatosAlumno[5]);
        jTextFieldOcupacion.setText(DatosAlumno[6]);
        jTextFieldTallaPantalon.setText(DatosAlumno[7]);
        jTextFieldTallaZapatos.setText(DatosAlumno[8]);
        jTextFieldTallaCamisa.setText(DatosAlumno[9]);
        principal.EliminarAlumno(cedula);
    }

    private int TipoIdentificacion(String TipoIdentificacion) {
        if(TipoIdentificacion.equals("Targeta identificacion")){
            return 1;
        }else if(TipoIdentificacion.equals("Cedula ciudadania")){
            return 2;
        }
        return 0;
    }

    
}

