/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author david
 */
public class Familia extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public int boton=0;
    public long cedula=0;
    public String nombreActual="";
    public String apellidoActual="";
    /**
     * Creates new form Familia
     */
    public Familia(Principal principal) {
        this.principal=principal;
        initComponents();
        jTextAreaSituacionFamiliar.setLineWrap(true);
        jTextAreaSituacionFamiliar.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFamilia = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelOcupacion = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldOcupacion = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelSituacionFamiliar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSituacionFamiliar = new javax.swing.JTextArea();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jTextFieldEdad = new javax.swing.JTextField();

        jLabelFamilia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelFamilia.setText("FAMILIA");

        jLabelApellido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellido");

        jLabelEdad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelEdad.setText("Edad");

        jLabelNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelOcupacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelOcupacion.setText("Ocupación");

        jLabelTelefono.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelTelefono.setText("Telefono");

        jLabelSituacionFamiliar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelSituacionFamiliar.setText("Situación Familiar");

        jTextAreaSituacionFamiliar.setColumns(20);
        jTextAreaSituacionFamiliar.setRows(5);
        jTextAreaSituacionFamiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextAreaSituacionFamiliar);

        jButtonSiguienteModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(475, 475, 475)
                        .addComponent(jButtonSiguienteModificar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTelefono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jLabelOcupacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNombre)
                                .addComponent(jLabelEdad))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabelApellido))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabelFamilia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabelSituacionFamiliar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFamilia)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOcupacion)
                    .addComponent(jTextFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSituacionFamiliar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonSiguienteModificar))
                .addGap(0, 19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        CambiarCrearModificar();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFamilia;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelOcupacion;
    private javax.swing.JLabel jLabelSituacionFamiliar;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSituacionFamiliar;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldOcupacion;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
    
    public void CambiarBoton(int cambio){
        boton=cambio;
        if(boton==1){
            jButtonSiguienteModificar.setText("Crear");
        }if(boton==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }
    public void CambiarPanel(int cambio){
        panel=cambio;
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
           principal.mostrarPanelPreFamilia();
           principal.CambioPreFamilia(1);
           principal.CambioCedulaPreFamilia(cedula);
           principal.CargarFamiliaSalud(cedula);
        }if(panel==2){
            principal.mostrarPanelPreFamilia();
            principal.CambioPreFamilia(2);
            principal.CambioCedulaPreFamilia(cedula);
            principal.CargarFamiliaSalud(cedula);
        }
    }
    private void CambiarCrearModificar() {
        if(boton==1){
            if(VerificarDatos()){
                if(FamiliarExiste()){
                    if(VerificarTelefono()){
                        if(VerificarCadena()){
                            String nombre = jTextFieldNombre.getText();
                            String apellido = jTextFieldApellido.getText();
                            int edad = Integer.parseInt(jTextFieldEdad.getText());
                            String ocupacion = jTextFieldOcupacion.getText();
                            long telefono=-1;
                            if(!(jTextFieldTelefono.getText().equals(""))){
                                telefono=Long.parseLong(jTextFieldTelefono.getText());
                            }
                            String situacionFamiliar = jTextAreaSituacionFamiliar.getText();
                            if(principal.CrearFamilia(nombre,apellido,edad,ocupacion,telefono,situacionFamiliar,cedula)){
                                principal.mostrarPanelPreFamilia();
                                if(panel==1){
                                    principal.CambioPreFamilia(1);
                                }if(panel==2){
                                    principal.CambioPreFamilia(2);
                                }
                                principal.CambioCedulaPreFamilia(cedula);
                                principal.CargarFamiliaSalud(cedula);
                            }else{
                                JOptionPane.showMessageDialog(this, "DATOS ERRONEOS");
                            }
                        }    
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "FAMILIAR YA EXISTENTE");
                }
            }   
        }if(boton==2){
            if(VerificarDatos()){
                if(FamiliarExisteSin()){
                    if(VerificarTelefono()){
                        if(VerificarCadena()){
                            String nombre = jTextFieldNombre.getText();
                            String apellido = jTextFieldApellido.getText();
                            int edad = Integer.parseInt(jTextFieldEdad.getText());
                            String ocupacion = jTextFieldOcupacion.getText();
                            long telefono=-1;
                            if(!(jTextFieldTelefono.getText().equals(""))){
                                telefono=Long.parseLong(jTextFieldTelefono.getText());
                            }
                            String situacionFamiliar = jTextAreaSituacionFamiliar.getText();
                            if(principal.ModificarFamilia(nombre,apellido,edad,ocupacion,telefono,situacionFamiliar,cedula,nombreActual,apellidoActual)){
                                principal.mostrarPanelPreFamilia();
                                if(panel==1){
                                    principal.CambioPreFamilia(1);
                                }if(panel==2){
                                    principal.CambioPreFamilia(2);
                                }
                                principal.CambioCedulaPreFamilia(cedula);
                                principal.CargarFamiliaSalud(cedula);
                            }else{
                                JOptionPane.showMessageDialog(this, "DATOS ERRONEOS");
                            }
                        }    
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "FAMILIAR YA EXISTENTE");
                }
            }   
        }
    }
    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }
    private boolean VerificarDatos() {
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE");
            return false;
        }else if(jTextFieldApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL APELLIDO");
            return false;
        }else if(jTextFieldEdad.equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA EDAD");
            return false;
        }else if(esNumero(jTextFieldEdad.getText())){
            JOptionPane.showMessageDialog(null, "EDAD ERRONEA");
            return false;
        }else if(jTextFieldOcupacion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA OCUPACION");
            return false;
        }
        return true;
    }
    private static boolean esNumero(String cadena) {
        try {
            Long.parseLong(cadena);
            return false;
        } catch (NumberFormatException nfe) {
            return true;
        }
    }
    private boolean FamiliarExiste() {
        return principal.FamiliarExiste(jTextFieldNombre.getText(),jTextFieldApellido.getText(),cedula);
    }
    private boolean VerificarTelefono() {
        if(!(jTextFieldTelefono.getText().equals(""))){
            if(esNumero(jTextFieldTelefono.getText())){
                JOptionPane.showMessageDialog(null, "NUMERO TELEFONICO ERRONEO");
                return false;
            }
        }
        return true;    
    }

    private boolean VerificarCadena() {
        if(((jTextFieldNombre.getText()).length())>25){
            JOptionPane.showMessageDialog(null, "NOMBRE EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldApellido.getText()).length())>25){
            JOptionPane.showMessageDialog(null, "APELLIDO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldEdad.getText()).length())>3){
            JOptionPane.showMessageDialog(null, "EDAD EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldTelefono.getText()).length())>15){
            JOptionPane.showMessageDialog(null, "TELEFONO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldOcupacion.getText()).length())>20){
            JOptionPane.showMessageDialog(null, "OCUPACION EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextAreaSituacionFamiliar.getText()).length())>295){
            JOptionPane.showMessageDialog(null, "SITUACION FAMILIAR EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }

    void CargarFamiliarModificar(String[] DatosFamiliar) {
        jTextFieldNombre.setText(DatosFamiliar[0]);
        nombreActual=DatosFamiliar[0];
        jTextFieldApellido.setText(DatosFamiliar[1]);
        apellidoActual=DatosFamiliar[1];
        jTextFieldEdad.setText(DatosFamiliar[2]);
        jTextFieldOcupacion.setText(DatosFamiliar[3]);
        if((Long.parseLong(DatosFamiliar[4]))!=-1){
            jTextFieldTelefono.setText(DatosFamiliar[4]);
        }
        jTextAreaSituacionFamiliar.setText(DatosFamiliar[5]);
    }

    private boolean FamiliarExisteSin() {
        return principal.FamiliarExisteSin(jTextFieldNombre.getText(),jTextFieldApellido.getText(),nombreActual,apellidoActual,cedula);
    }
}
