/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
/**
 *
 * @author david
 */
public class Home extends javax.swing.JPanel {
    private Principal principal;
    /**
     * Creates new form Home
     */
    public Home(Principal principal) {
        this.principal=principal;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificacion = new javax.swing.JButton();
        jButtonRegistro = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonConsultas = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jLabelModificacion = new javax.swing.JLabel();
        jLabelConsultas = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jButtonObservaciones = new javax.swing.JButton();
        jLabelObservaciones = new javax.swing.JLabel();
        jButtonTalleres = new javax.swing.JButton();
        jLabelConsultas1 = new javax.swing.JLabel();

        jButtonModificacion.setText("2");
        jButtonModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificacionActionPerformed(evt);
            }
        });

        jButtonRegistro.setText("1");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("6");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonConsultas.setText("4");
        jButtonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultasActionPerformed(evt);
            }
        });

        jLabelRegistro.setText("Registro");

        jLabelModificacion.setText("Modificacion");

        jLabelConsultas.setText("Consultas");

        jLabelSalir.setText("Salir");

        jButtonObservaciones.setText("3");
        jButtonObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObservacionesActionPerformed(evt);
            }
        });

        jLabelObservaciones.setText("Observaciones");

        jButtonTalleres.setText("5");
        jButtonTalleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTalleresActionPerformed(evt);
            }
        });

        jLabelConsultas1.setText("Talleres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabelRegistro)))
                        .addComponent(jButtonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelConsultas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelModificacion))
                            .addComponent(jButtonTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelObservaciones)
                            .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelConsultas1)
                        .addGap(144, 144, 144)
                        .addComponent(jLabelSalir)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistro)
                    .addComponent(jLabelModificacion)
                    .addComponent(jLabelObservaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultas)
                    .addComponent(jLabelSalir)
                    .addComponent(jLabelConsultas1))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        principal.mostrarPanelLogin();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        principal.mostrarPanelDatosPersonales();
        principal.CambioDatosPersonales(1);
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jButtonModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificacionActionPerformed
        principal.mostrarPanelModificar();
    }//GEN-LAST:event_jButtonModificacionActionPerformed

    private void jButtonObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObservacionesActionPerformed
        principal.mostrarPanelObservaciones();
    }//GEN-LAST:event_jButtonObservacionesActionPerformed

    private void jButtonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultasActionPerformed
        principal.mostrarPanelConsultas();
    }//GEN-LAST:event_jButtonConsultasActionPerformed

    private void jButtonTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTalleresActionPerformed
        CargarPreTalleres();
    }//GEN-LAST:event_jButtonTalleresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonModificacion;
    private javax.swing.JButton jButtonObservaciones;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JButton jButtonTalleres;
    private javax.swing.JLabel jLabelConsultas;
    private javax.swing.JLabel jLabelConsultas1;
    private javax.swing.JLabel jLabelModificacion;
    private javax.swing.JLabel jLabelObservaciones;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelSalir;
    // End of variables declaration//GEN-END:variables

    private void CargarPreTalleres() {
        principal.mostrarPanelPreTalleres();
        principal.CargarTalleres();
    }
}
