/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
/**
 *
 * @author david
 */
public class Modificar extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    /**
     * Creates new form Modificar
     */
    public Modificar(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosPersonales2 = new javax.swing.JLabel();
        jLabelModificar = new javax.swing.JLabel();
        jButtonDatosPersonales = new javax.swing.JButton();
        jButtonUbicacionContacto = new javax.swing.JButton();
        jButtonPerfilAcademico = new javax.swing.JButton();
        jButtonSalud = new javax.swing.JButton();
        jButtonFamilia = new javax.swing.JButton();
        jButtonInscripcion = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxEstudiantes = new javax.swing.JComboBox<>();
        jButtonVolver = new javax.swing.JButton();

        jLabelDatosPersonales2.setText("Datos personales");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelModificar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelModificar.setText("MODIFICAR ESTUDIANTES");
        add(jLabelModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jButtonDatosPersonales.setText("Datos Personales");
        jButtonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosPersonalesActionPerformed(evt);
            }
        });
        add(jButtonDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 145, 40));

        jButtonUbicacionContacto.setText("Ubicación y Contacto");
        jButtonUbicacionContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbicacionContactoActionPerformed(evt);
            }
        });
        add(jButtonUbicacionContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 145, 40));

        jButtonPerfilAcademico.setText("Perfil Academico");
        jButtonPerfilAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilAcademicoActionPerformed(evt);
            }
        });
        add(jButtonPerfilAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 145, 40));

        jButtonSalud.setText("Salud");
        jButtonSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaludActionPerformed(evt);
            }
        });
        add(jButtonSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 145, 40));

        jButtonFamilia.setText("Familia");
        jButtonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFamiliaActionPerformed(evt);
            }
        });
        add(jButtonFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 145, 40));

        jButtonInscripcion.setText("Inscripción");
        jButtonInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscripcionActionPerformed(evt);
            }
        });
        add(jButtonInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 145, 40));

        jTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 190, 28));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar");
        add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jComboBoxEstudiantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jComboBoxEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 190, 28));

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.mostrarPanelHome();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        mostrarPanelDatosPersonales();       
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonUbicacionContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbicacionContactoActionPerformed
        mostrarPanelUbicacionContacto();
    }//GEN-LAST:event_jButtonUbicacionContactoActionPerformed

    private void jButtonPerfilAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilAcademicoActionPerformed
        mostrarPanelPerfilAcademico();
    }//GEN-LAST:event_jButtonPerfilAcademicoActionPerformed

    private void jButtonSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaludActionPerformed
        mostrarPanelSalud();
    }//GEN-LAST:event_jButtonSaludActionPerformed

    private void jButtonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFamiliaActionPerformed
        mostrarPanelFamilia();
    }//GEN-LAST:event_jButtonFamiliaActionPerformed

    private void jButtonInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscripcionActionPerformed
        mostrarPanelInscripcion();
    }//GEN-LAST:event_jButtonInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonFamilia;
    private javax.swing.JButton jButtonInscripcion;
    private javax.swing.JButton jButtonPerfilAcademico;
    private javax.swing.JButton jButtonSalud;
    private javax.swing.JButton jButtonUbicacionContacto;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstudiantes;
    private javax.swing.JLabel jLabelDatosPersonales2;
    private javax.swing.JLabel jLabelModificar;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanelDatosPersonales() {
        principal.mostrarPanelDatosPersonales();
        principal.CambioDatosPersonales(2);
    }

    private void mostrarPanelUbicacionContacto() {
        principal.mostrarPanelContacto();
        principal.CambioContacto(2);
    }

    private void mostrarPanelPerfilAcademico() {
        principal.mostrarPanelPerfilAcademico();
        principal.CambioPerfilAcademico(2);
    }

    private void mostrarPanelSalud() {
        principal.mostrarPanelSalud();
        principal.CambioSalud(2);
    }

    private void mostrarPanelFamilia() {
        principal.mostrarPanelPreFamilia();
        principal.CambioPreFamilia(2);
    }

    private void mostrarPanelInscripcion() {
        principal.mostrarPanelInscripcion();
        principal.CambioInscripcion(2);
    }

}
