/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
/**
 *
 * @author david
 */
public class Modificar extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    /**
     * Creates new form Modificar
     */
    public Modificar(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosPersonales2 = new javax.swing.JLabel();
        jLabelModificar = new javax.swing.JLabel();
        jButtonDatosPersonales = new javax.swing.JButton();
        jLabelDatosPersonales = new javax.swing.JLabel();
        jButtonUbicacionContacto = new javax.swing.JButton();
        jButtonPerfilAcademico = new javax.swing.JButton();
        jButtonSalud = new javax.swing.JButton();
        jButtonFamilia = new javax.swing.JButton();
        jButtonInscripcion = new javax.swing.JButton();
        jLabelUbicacionContacto = new javax.swing.JLabel();
        jLabelPerfilAcademico = new javax.swing.JLabel();
        jLabelSalud = new javax.swing.JLabel();
        jLabelFamilia = new javax.swing.JLabel();
        jLabelInscripcion = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxEstudiantes = new javax.swing.JComboBox<>();
        jButtonVolver = new javax.swing.JButton();

        jLabelDatosPersonales2.setText("Datos personales");

        jLabelModificar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelModificar.setText("MODIFICAR");

        jButtonDatosPersonales.setText("1");
        jButtonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosPersonalesActionPerformed(evt);
            }
        });

        jLabelDatosPersonales.setText("Datos personales");

        jButtonUbicacionContacto.setText("2");
        jButtonUbicacionContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbicacionContactoActionPerformed(evt);
            }
        });

        jButtonPerfilAcademico.setText("3");
        jButtonPerfilAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilAcademicoActionPerformed(evt);
            }
        });

        jButtonSalud.setText("4");
        jButtonSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaludActionPerformed(evt);
            }
        });

        jButtonFamilia.setText("5");
        jButtonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFamiliaActionPerformed(evt);
            }
        });

        jButtonInscripcion.setText("6");
        jButtonInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscripcionActionPerformed(evt);
            }
        });

        jLabelUbicacionContacto.setText("Ubicacion y Contacto");

        jLabelPerfilAcademico.setText("Perfil Academico");

        jLabelSalud.setText("Salud");

        jLabelFamilia.setText("Familia");

        jLabelInscripcion.setText("Inscripcion");

        jButtonBuscar.setText("Buscar");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDatosPersonales)
                                    .addComponent(jButtonDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelUbicacionContacto)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonUbicacionContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButtonFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelSalud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFamilia)
                                .addGap(111, 111, 111)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPerfilAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPerfilAcademico)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelInscripcion))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jButtonVolver)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelModificar)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbicacionContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPerfilAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosPersonales)
                    .addComponent(jLabelUbicacionContacto)
                    .addComponent(jLabelPerfilAcademico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalud)
                    .addComponent(jLabelFamilia)
                    .addComponent(jLabelInscripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.mostrarPanelHome();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        mostrarPanelDatosPersonales();       
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonUbicacionContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbicacionContactoActionPerformed
        mostrarPanelUbicacionContacto();
    }//GEN-LAST:event_jButtonUbicacionContactoActionPerformed

    private void jButtonPerfilAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilAcademicoActionPerformed
        mostrarPanelPerfilAcademico();
    }//GEN-LAST:event_jButtonPerfilAcademicoActionPerformed

    private void jButtonSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaludActionPerformed
        mostrarPanelSalud();
    }//GEN-LAST:event_jButtonSaludActionPerformed

    private void jButtonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFamiliaActionPerformed
        mostrarPanelFamilia();
    }//GEN-LAST:event_jButtonFamiliaActionPerformed

    private void jButtonInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscripcionActionPerformed
        mostrarPanelInscripcion();
    }//GEN-LAST:event_jButtonInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonFamilia;
    private javax.swing.JButton jButtonInscripcion;
    private javax.swing.JButton jButtonPerfilAcademico;
    private javax.swing.JButton jButtonSalud;
    private javax.swing.JButton jButtonUbicacionContacto;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstudiantes;
    private javax.swing.JLabel jLabelDatosPersonales;
    private javax.swing.JLabel jLabelDatosPersonales2;
    private javax.swing.JLabel jLabelFamilia;
    private javax.swing.JLabel jLabelInscripcion;
    private javax.swing.JLabel jLabelModificar;
    private javax.swing.JLabel jLabelPerfilAcademico;
    private javax.swing.JLabel jLabelSalud;
    private javax.swing.JLabel jLabelUbicacionContacto;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanelDatosPersonales() {
        principal.mostrarPanelDatosPersonales();
        principal.CambioDatosPersonales(2);
    }

    private void mostrarPanelUbicacionContacto() {
        principal.mostrarPanelContacto();
        principal.CambioContacto(2);
    }

    private void mostrarPanelPerfilAcademico() {
        principal.mostrarPanelPerfilAcademico();
        principal.CambioPerfilAcademico(2);
    }

    private void mostrarPanelSalud() {
        principal.mostrarPanelSalud();
        principal.CambioSalud(2);
    }

    private void mostrarPanelFamilia() {
        principal.mostrarPanelPreFamilia();
        principal.CambioPreFamilia(2);
    }

    private void mostrarPanelInscripcion() {
        principal.mostrarPanelInscripcion();
        principal.CambioInscripcion(2);
    }

}
