/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Observacion extends javax.swing.JPanel {
    private Principal principal;
    public long cedula=0;
    public int dato=-1;
    /**
     * Creates new form ObservacionesCrear
     */
    public Observacion(Principal principal) {
        this.principal=principal;
        initComponents();
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelObservacion = new javax.swing.JLabel();
        jLabelNombreEstudiante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jButtonCrear = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelObservacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelObservacion.setText("OBSERVACIÓN");

        jLabelNombreEstudiante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNombreEstudiante.setText("NOMBRE ESTUDIANTE");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jButtonCrear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCrear.setText("Guardar");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrear)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelNombreEstudiante)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelObservacion)
                        .addGap(260, 260, 260))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelObservacion)
                .addGap(48, 48, 48)
                .addComponent(jLabelNombreEstudiante)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonVolver))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        CargarAlumnoObservaciones();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        GuardarObservacion();
    }//GEN-LAST:event_jButtonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelNombreEstudiante;
    private javax.swing.JLabel jLabelObservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    // End of variables declaration//GEN-END:variables
    private void CargarAlumnoObservaciones(){
        principal.mostrarPanelObservaciones();
        principal.CargarAlumnoObservaciones();
    }
    public void CambioCedulaObervacion(Long cedula,String nombre,String apellido){
        this.cedula=cedula;
        String nombreCompleto=nombre+" "+apellido;
        jLabelNombreEstudiante.setText(nombreCompleto);
    }
    public void CambioDatoObservacion(int cambio){
        dato=cambio;
    }
    
    private void GuardarObservacion() {
        if(dato==-1){
            if(validar()){
                String descripcion=jTextAreaDescripcion.getText();
                if(principal.CrearObservacion(descripcion,cedula)){
                    principal.mostrarPanelObservaciones();
                    principal.CargarAlumnoObservaciones();
                }else{
                    JOptionPane.showMessageDialog(null, "Observación fallida");
                }
            }
        }else{
            if(validar()){
                String descripcion=jTextAreaDescripcion.getText();
                if(principal.ModificarObservacion(descripcion,dato,cedula)){
                    principal.mostrarPanelObservaciones();
                    principal.CargarAlumnoObservaciones();
                }else{
                    JOptionPane.showMessageDialog(null, "Observación fallida");
                }
            }
        }
    }

    private boolean validar() {
        if((jTextAreaDescripcion.getText()).equals("")){
            JOptionPane.showMessageDialog(null, "ESCRIBA DESCRIPCION");
            return false;
        }else if(((jTextAreaDescripcion.getText()).length())>240){
            JOptionPane.showMessageDialog(null, "DESCRIPCIÓN EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }

    void CargarObservacion(String DatosObservacion) {
        jTextAreaDescripcion.setText(DatosObservacion);
    }
}
