/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class PerfilAcademico extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /**
     * Creates new form PerfilAcademico
     */
    public PerfilAcademico(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPerfilAcademico = new javax.swing.JLabel();
        jLabelNivelEscolar = new javax.swing.JLabel();
        jTextFieldInstitucionEducatica = new javax.swing.JTextField();
        jLabelGrado = new javax.swing.JLabel();
        jLabelInstitucionEducativa = new javax.swing.JLabel();
        jTextFieldGrado = new javax.swing.JTextField();
        jTextFieldNivelEscolar = new javax.swing.JTextField();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelPerfilAcademico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPerfilAcademico.setText("PERFIL ACADEMICO");

        jLabelNivelEscolar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNivelEscolar.setText("Nivel escolar");

        jTextFieldInstitucionEducatica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelGrado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelGrado.setText("Grado");

        jLabelInstitucionEducativa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelInstitucionEducativa.setText("Institución educativa");

        jTextFieldGrado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldNivelEscolar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButtonSiguienteModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(178, 178, 178)
                        .addComponent(jButtonSiguienteModificar)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNivelEscolar)
                            .addComponent(jLabelInstitucionEducativa)
                            .addComponent(jLabelGrado))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldInstitucionEducatica)
                            .addComponent(jTextFieldNivelEscolar)
                            .addComponent(jTextFieldGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPerfilAcademico)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPerfilAcademico)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInstitucionEducativa)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabelGrado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldInstitucionEducatica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldNivelEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jTextFieldGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguienteModificar)
                    .addComponent(jButtonVolver))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelGrado;
    private javax.swing.JLabel jLabelInstitucionEducativa;
    private javax.swing.JLabel jLabelNivelEscolar;
    private javax.swing.JLabel jLabelPerfilAcademico;
    private javax.swing.JTextField jTextFieldGrado;
    private javax.swing.JTextField jTextFieldInstitucionEducatica;
    private javax.swing.JTextField jTextFieldNivelEscolar;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                if(VerifivarCadena()){
                    String institucionEducativa = jTextFieldInstitucionEducatica.getText();
                    String nivelEscolar = jTextFieldNivelEscolar.getText();
                    String grado = jTextFieldGrado.getText();
                    if(principal.CrearPerfilAcademico(institucionEducativa,nivelEscolar,grado,cedula)){
                        principal.mostrarPanelSalud();
                        principal.CambioSalud(1);  
                        principal.CambioCedulaSalud(cedula);
                    }else{
                        JOptionPane.showMessageDialog(this, "Datos erroenos"); 
                    }
                }    
            }
        }if(panel==2){
            if(VerificarDatos()){
                if(VerifivarCadena()){
                    String institucionEducativa = jTextFieldInstitucionEducatica.getText();
                    String nivelEscolar = jTextFieldNivelEscolar.getText();
                    String grado = jTextFieldGrado.getText();
                    if(principal.ModificarPerfilAcademico(institucionEducativa,nivelEscolar,grado,cedula)){
                        principal.mostrarPanelModificar();
                        principal.CargarAlumnos();
                    }else{
                        JOptionPane.showMessageDialog(this, "Datos erroenos"); 
                    }
                }    
            }
        }
    }
    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }
    private void cambiarVolver() {
        if(panel==1){
            principal.mostrarPanelContacto();
            principal.CambioContacto(1);
            principal.CambioCedulaContacto(cedula);
            principal.CargarContacto(cedula);
        }if(panel==2){
            principal.mostrarPanelModificar();
            principal.CargarAlumnos();
        }
    }
    private boolean VerificarDatos() {
        if(jTextFieldNivelEscolar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL NIVEL ESCOLAR");
            return false;
        }
        return true;
    }
    void CargarPerfilAcademico(String[] DatosPerfilAcademico) {
        jTextFieldNivelEscolar.setText(DatosPerfilAcademico[0]);
        jTextFieldGrado.setText(DatosPerfilAcademico[1]);
        jTextFieldInstitucionEducatica.setText(DatosPerfilAcademico[2]);
        principal.EliminarPerfilAcademico(cedula);
    }
    void CargarPerfilAcademicoModificar(String[] DatosPerfilAcademico) {
        jTextFieldNivelEscolar.setText(DatosPerfilAcademico[0]);
        jTextFieldGrado.setText(DatosPerfilAcademico[1]);
        jTextFieldInstitucionEducatica.setText(DatosPerfilAcademico[2]);
    }

    private boolean VerifivarCadena() {
        if(((jTextFieldInstitucionEducatica.getText()).length())>78){
            JOptionPane.showMessageDialog(null, "INSTITUCION EDUCATIVA EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldNivelEscolar.getText()).length())>45){
            JOptionPane.showMessageDialog(null, "NIVEL ESCOLAR EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextFieldGrado.getText()).length())>17){
            JOptionPane.showMessageDialog(null, "GRADO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }
}
