/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author david
 */
public class PreFamilia extends javax.swing.JPanel {
    private Principal principal;
    
    public int panel=0;
    public long cedula=0;
    
    /**
     * Creates new form PreFamilia
     */
    public PreFamilia(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFamilia = new javax.swing.JTable();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFamilia = new javax.swing.JLabel();

        jTableFamilia = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableFamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFamilia.setFocusable(false);
        jTableFamilia.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableFamilia);

        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonVolver.setText("volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabelFamilia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelFamilia.setText("FAMILIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabelFamilia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrear)
                .addGap(110, 110, 110)
                .addComponent(jButtonSiguienteModificar)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFamilia)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguienteModificar)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonVolver))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        CambiarFamilia();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFamilia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFamilia;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
            
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
            
        }
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
            principal.mostrarPanelInscripcion();
            principal.CambioInscripcion(1);
            principal.CambioCedulaInscripcion(cedula);
            principal.CargarCursos();
        }if(panel==2){
            principal.mostrarPanelFamilia();
            principal.CambioFamilia(2);
        }
    }
    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }
    private void cambiarVolver() {
        if(panel==1){
            principal.mostrarPanelSalud();
            principal.CambioSalud(1);
            principal.EliminarFamilia(cedula);
            principal.CambioCedulaSalud(cedula);
            principal.CargarSalud(cedula);
        }if(panel==2){
            principal.mostrarPanelModificar();
        }
    }

    public void cargarTabla() {
        DefaultTableModel modeloTabla= (DefaultTableModel) jTableFamilia.getModel();
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("apellido");
        modeloTabla.addColumn("ocupacion");
        modeloTabla.addColumn("telefono");
        int c=principal.ObtenerNumeroFamiliares(cedula);
        int x=0;
        Object [][]datos=new Object[c][4];
        datos=principal.CargarFamiliaAlumno(cedula);
        while(x<c){
            if(datos[x][3].equals("-1")){
                    datos[x][3]="";
            }
            Object row[]= {datos[x][0],datos[x][1],datos[x][2],datos[x][3]};
            ((DefaultTableModel)jTableFamilia.getModel()).addRow(row);
            x++;
        }
        
    }
    private void CambiarFamilia(){
        principal.mostrarPanelFamilia();
        principal.CambioFamilia(1);
        principal.CambioCedulaFamilia(cedula);
    }
    class CustomTableModel extends DefaultTableModel {
    @Override
        public boolean isCellEditable(int row, int column) {
          return false;
        }
    }
    
}
