/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author david
 */
public class PreTalleres extends javax.swing.JPanel {
    private Principal principal;
    public int seleccionTaller=-1;
    /**
     * Creates new form Talleres
     */
    public PreTalleres(Principal principal) {
        this.principal=principal;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTalleres = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTalleres = new javax.swing.JTable();

        jLabelTalleres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTalleres.setText("TALLERES");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jTableTalleres = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableTalleres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTalleres.setFocusable(false);
        jTableTalleres.getTableHeader().setReorderingAllowed(false);
        jTableTalleres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTalleresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTalleres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonVolver)
                .addGap(124, 124, 124)
                .addComponent(jButtonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrear)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTalleres)
                .addGap(245, 245, 245))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTalleres)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonModificar))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.mostrarPanelHome();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        CargarCrearTaller();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        CargarModificarTaller();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTableTalleresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTalleresMouseClicked
         seleccionTaller= evt.getY() /jTableTalleres.getRowHeight();  
    }//GEN-LAST:event_jTableTalleresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelTalleres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTalleres;
    // End of variables declaration//GEN-END:variables

    private void CargarCrearTaller() {
        principal.mostrarPanelTalleres();
        principal.CambioTalleres(1);
    }
    private void CargarModificarTaller() {
        if(seleccionTaller!=-1){
            principal.mostrarPanelTalleres();
            principal.CambioTalleres(2);
            principal.CargarTaller((String) jTableTalleres.getValueAt(seleccionTaller, 0));
        }else{
            JOptionPane.showMessageDialog(this, "ELEGIR TALLER");
        }    
    }
    public void cargarTabla() {
        DefaultTableModel modeloTabla= (DefaultTableModel) jTableTalleres.getModel();
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("estado");
        modeloTabla.addColumn("cupos");
        int c=principal.ObtenerNumeroTalleres();
        int x=0;
        Object [][]datos=new Object[c][3];
        datos=principal.CargarTallere();
        while(x<c){
            if(datos[x][1].equals("1")){
                    datos[x][1]="Activo";
            }else{
                datos[x][1]="Inactivo";
            }
            if(datos[x][2].equals("-1")){
                    datos[x][2]="";
            }
            Object row[]= {datos[x][0],datos[x][1],datos[x][2]};
            ((DefaultTableModel)jTableTalleres.getModel()).addRow(row);
            x++;
        }
        
    }
}
