/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Reubicacion extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    public String []cursos;
    /**
     * Creates new form Reubicacion
     */
    public Reubicacion(Principal principal) {
        this.principal=principal;
        initComponents();
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReubicacion = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        jLabelReubicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelReubicacion.setText("RE-UBICACIÓN");

        jLabelUbicacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelUbicacion.setText("Ubicación");

        jTextFieldUbicacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabelDescripcion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelDescripcion.setText("Descripción");

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabelUbicacion)
                .addGap(34, 34, 34)
                .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabelDescripcion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelReubicacion)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReubicacion)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUbicacion)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonGuardar))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        CambiarInscripcion();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        CrearReubicacion();
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelReubicacion;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables

    void CambioReubicacion(int panel, long cedula) {
        this.panel =panel;
        this.cedula = cedula;
    }

    private void CambiarInscripcion() {
        principal.mostrarPanelInscripcion();
        principal.CambioCedulaInscripcion(cedula);
        principal.CambioInscripcion(panel);
        principal.CargarCambiosInscripcion();
        if(panel==2){
            principal.GuardarInscripcionAlumno(cursos);
        }    
    }

    void CargarReubicacion(String[] DatosReubicacion) {
        jTextFieldUbicacion.setText(DatosReubicacion[0]);
        jTextAreaDescripcion.setText(DatosReubicacion[1]);
    }

    private void CrearReubicacion() {
        if(principal.ReubicacionExiste(cedula)){
            if(Validar()){
                if(ValidarCadenas()){
                    String ubicacion = jTextFieldUbicacion.getText();
                    String Descripcion = jTextAreaDescripcion.getText();
                    if(principal.CrearReubicacion(ubicacion,Descripcion,cedula)){
                        principal.mostrarPanelInscripcion();
                        principal.CambioCedulaInscripcion(cedula);
                        principal.CambioInscripcion(panel);
                        principal.CargarCambiosInscripcion();
                        if(panel==2){
                            principal.GuardarInscripcionAlumno(cursos);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "REGISTRO ERRONEO");
                    }
                }    
            }
        }else{
            if(Validar()){
                if(ValidarCadenas()){
                    String ubicacion = jTextFieldUbicacion.getText();
                    String Descripcion = jTextAreaDescripcion.getText();
                    if(principal.ModificarReubicacion(ubicacion,Descripcion,cedula)){
                        principal.mostrarPanelInscripcion();
                        principal.CambioCedulaInscripcion(cedula);
                        principal.CambioInscripcion(panel);
                        principal.CargarCambiosInscripcion();
                        if(panel==2){
                            principal.GuardarInscripcionAlumno(cursos);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "REGISTRO ERRONEO");
                    }
                }    
            }
        }
    }   

    private boolean Validar() {
        if(jTextAreaDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA DESCRIPCION");
            return false;
        }
        return true;
    }

    void GuardarCursosAlumno(String[] cursosInscritos) {
        cursos=cursosInscritos;
    }

    private boolean ValidarCadenas() {
        if(((jTextFieldUbicacion.getText()).length())>78){
            JOptionPane.showMessageDialog(null, "UBICACION EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextAreaDescripcion.getText()).length())>295){
            JOptionPane.showMessageDialog(null, "DESCRIPCION EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }

  
    
}
