/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Salud extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /**
     * Creates new form Salud
     */
    public Salud(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSalud = new javax.swing.JLabel();
        jLabelConvenio = new javax.swing.JLabel();
        jTextFieldConvenio = new javax.swing.JTextField();
        jLabelGrupo = new javax.swing.JLabel();
        jLabelSanguineo = new javax.swing.JLabel();
        jComboBoxGrupoSanguineo = new javax.swing.JComboBox<>();
        jLabelRH = new javax.swing.JLabel();
        jComboBoxRH = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMedicamentos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRecomendaciones = new javax.swing.JTextArea();
        jLabelDiagnostico = new javax.swing.JLabel();
        jLabelRecomendaciones = new javax.swing.JLabel();
        jLabelMedicamentos = new javax.swing.JLabel();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelSalud.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSalud.setText("SALUD");

        jLabelConvenio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelConvenio.setText("Afiliacion en salud");

        jTextFieldConvenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelGrupo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelGrupo.setText("Grupo");

        jLabelSanguineo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelSanguineo.setText("Sanguineo");

        jComboBoxGrupoSanguineo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabelRH.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelRH.setText("RH");

        jComboBoxRH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextAreaDiagnostico.setColumns(20);
        jTextAreaDiagnostico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaDiagnostico.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDiagnostico);

        jTextAreaMedicamentos.setColumns(20);
        jTextAreaMedicamentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaMedicamentos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMedicamentos);

        jTextAreaRecomendaciones.setColumns(20);
        jTextAreaRecomendaciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaRecomendaciones.setRows(5);
        jScrollPane3.setViewportView(jTextAreaRecomendaciones);

        jLabelDiagnostico.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelDiagnostico.setText("Diagnostico");

        jLabelRecomendaciones.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelRecomendaciones.setText("Recomendación");

        jLabelMedicamentos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelMedicamentos.setText("Medicamentos");

        jButtonSiguienteModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSanguineo)
                            .addComponent(jLabelGrupo)
                            .addComponent(jLabelSalud))
                        .addGap(43, 43, 43)
                        .addComponent(jComboBoxGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabelRH)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButtonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelDiagnostico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMedicamentos)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRecomendaciones)
                    .addComponent(jButtonSiguienteModificar))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSalud)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSanguineo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRH)
                            .addComponent(jComboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRecomendaciones)
                    .addComponent(jLabelMedicamentos)
                    .addComponent(jLabelDiagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguienteModificar)
                    .addComponent(jButtonVolver))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxGrupoSanguineo;
    private javax.swing.JComboBox<String> jComboBoxRH;
    private javax.swing.JLabel jLabelConvenio;
    private javax.swing.JLabel jLabelDiagnostico;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelMedicamentos;
    private javax.swing.JLabel jLabelRH;
    private javax.swing.JLabel jLabelRecomendaciones;
    private javax.swing.JLabel jLabelSalud;
    private javax.swing.JLabel jLabelSanguineo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnostico;
    private javax.swing.JTextArea jTextAreaMedicamentos;
    private javax.swing.JTextArea jTextAreaRecomendaciones;
    private javax.swing.JTextField jTextFieldConvenio;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }
    private void CargarComboBox() {
        String GrupoSanguineo[] = { "","A","B","AB","O"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(GrupoSanguineo);
        jComboBoxGrupoSanguineo.setModel(model);
        String RH[] = { "","-","+"};
        final DefaultComboBoxModel model1 = new DefaultComboBoxModel(RH);
        jComboBoxRH.setModel(model1);
        jTextAreaDiagnostico.setLineWrap(true);
        jTextAreaDiagnostico.setWrapStyleWord(true);
        jTextAreaMedicamentos.setLineWrap(true);
        jTextAreaMedicamentos.setWrapStyleWord(true);
        jTextAreaRecomendaciones.setLineWrap(true);
        jTextAreaRecomendaciones.setWrapStyleWord(true);
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                if(VerificarCadenas()){
                    String afiliacionSalud = jTextFieldConvenio.getText();
                    String grupoSanguineo=(String) jComboBoxGrupoSanguineo.getSelectedItem();
                    String rH=(String) jComboBoxRH.getSelectedItem();
                    String diagnostico = jTextAreaDiagnostico.getText();
                    String medicamentos = jTextAreaMedicamentos.getText();
                    String recomendaciones = jTextAreaRecomendaciones.getText();
                    if(principal.CrearSalud(afiliacionSalud,grupoSanguineo,rH,diagnostico,medicamentos,recomendaciones,cedula)){
                        principal.mostrarPanelPreFamilia();
                        principal.CambioPreFamilia(1);
                        principal.CambioCedulaPreFamilia(cedula);
                        principal.CargarFamiliaSalud(cedula);
                    }else{
                        JOptionPane.showMessageDialog(null, "DATOS ERRONEOS");
                    }
                }    
            }    
        }if(panel==2){
            if(VerificarDatos()){
                if(VerificarCadenas()){
                    String afiliacionSalud = jTextFieldConvenio.getText();
                    String grupoSanguineo=(String) jComboBoxGrupoSanguineo.getSelectedItem();
                    String rH=(String) jComboBoxRH.getSelectedItem();
                    String diagnostico = jTextAreaDiagnostico.getText();
                    String medicamentos = jTextAreaMedicamentos.getText();
                    String recomendaciones = jTextAreaRecomendaciones.getText();
                    if(principal.ModificarSalud(afiliacionSalud,grupoSanguineo,rH,diagnostico,medicamentos,recomendaciones,cedula)){
                        principal.mostrarPanelModificar();
                        principal.CargarAlumnos();
                    }else{
                        JOptionPane.showMessageDialog(null, "DATOS ERRONEOS");
                    }
                }    
            }    
        }
    }
    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }
    private void cambiarVolver() {
        if(panel==1){
            principal.mostrarPanelPerfilAcademico();
            principal.CambioPerfilAcademico(1);
            principal.CambioCedulaPerfilAcademico(cedula);
            principal.CargarPerfilAcademico(cedula);
        }if(panel==2){
            principal.mostrarPanelModificar();
            principal.CargarAlumnos();
        }
    }
    private boolean VerificarDatos() {
        if(jTextFieldConvenio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA AFILIACION DE SALUD");
            return false;
        }else if(((String) jComboBoxGrupoSanguineo.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE GRUPO SANGUINEO");
            return false;
        }else if(((String) jComboBoxRH.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE RH");
            return false;
        }
        return true;
    }
    void CargarSalud(String[] DatosSalud) {
        jTextFieldConvenio.setText(DatosSalud[0]);
        jComboBoxGrupoSanguineo.setSelectedIndex(TipoGrupoSanguineo(DatosSalud[1]));
        jComboBoxRH.setSelectedIndex(TipoRH(DatosSalud[2]));;
        jTextAreaDiagnostico.setText(DatosSalud[3]);
        jTextAreaMedicamentos.setText(DatosSalud[4]);
        jTextAreaRecomendaciones.setText(DatosSalud[5]);
        principal.EliminarSalud(cedula);
    }
    void CargarSaludModificar(String[] DatosSalud) {
        jTextFieldConvenio.setText(DatosSalud[0]);
        jComboBoxGrupoSanguineo.setSelectedIndex(TipoGrupoSanguineo(DatosSalud[1]));
        jComboBoxRH.setSelectedIndex(TipoRH(DatosSalud[2]));;
        jTextAreaDiagnostico.setText(DatosSalud[3]);
        jTextAreaMedicamentos.setText(DatosSalud[4]);
        jTextAreaRecomendaciones.setText(DatosSalud[5]);
    }
    private int TipoGrupoSanguineo(String grupoSanguineo) {
        if(grupoSanguineo.equals("A")){
            return 1;
        }else if(grupoSanguineo.equals("B")){
            return 2;
        }else if(grupoSanguineo.equals("AB")){
            return 3;
        }else if(grupoSanguineo.equals("O")){
            return 4;
        }
        return 0;
    }
    private int TipoRH(String RH) {
        if(RH.equals("-")){
            return 1;
        }else if(RH.equals("+")){
            return 2;
        }
        return 0;
    }

    private boolean VerificarCadenas() {
        if(((jTextFieldConvenio.getText()).length())>30){
            JOptionPane.showMessageDialog(null, "AFILIACION EN SALUD EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextAreaDiagnostico.getText()).length())>295){
            JOptionPane.showMessageDialog(null, "DIAGNOSTICO EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextAreaMedicamentos.getText()).length())>195){
            JOptionPane.showMessageDialog(null, "MEDICAMENTOS EXCEDE EL TAMAÑO VALIDO");
            return false;
        }else if(((jTextAreaRecomendaciones.getText()).length())>295){
            JOptionPane.showMessageDialog(null, "RECOMENDACIONES EXCEDE EL TAMAÑO VALIDO");
            return false;
        }
        return true;
    }
}
