/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Salud extends javax.swing.JPanel {
    private Principal principal;
    public int panel=0;
    public long cedula=0;
    /**
     * Creates new form Salud
     */
    public Salud(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSalud = new javax.swing.JLabel();
        jLabelConvenio = new javax.swing.JLabel();
        jTextFieldConvenio = new javax.swing.JTextField();
        jLabelGrupo = new javax.swing.JLabel();
        jLabelSanguineo = new javax.swing.JLabel();
        jComboBoxGrupoSanguineo = new javax.swing.JComboBox<>();
        jLabelRH = new javax.swing.JLabel();
        jComboBoxRH = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMedicamentos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRecomendaciones = new javax.swing.JTextArea();
        jLabelDiagnostico = new javax.swing.JLabel();
        jLabelRecomendaciones = new javax.swing.JLabel();
        jLabelMedicamentos = new javax.swing.JLabel();
        jButtonSiguienteModificar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        jLabelSalud.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSalud.setText("SALUD");

        jLabelConvenio.setText("Afiliacion en salud");

        jLabelGrupo.setText("Grupo");

        jLabelSanguineo.setText("Sanguineo");

        jLabelRH.setText("RH");

        jTextAreaDiagnostico.setColumns(20);
        jTextAreaDiagnostico.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDiagnostico);

        jTextAreaMedicamentos.setColumns(20);
        jTextAreaMedicamentos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMedicamentos);

        jTextAreaRecomendaciones.setColumns(20);
        jTextAreaRecomendaciones.setRows(5);
        jScrollPane3.setViewportView(jTextAreaRecomendaciones);

        jLabelDiagnostico.setText("Diagnostico");

        jLabelRecomendaciones.setText("Recomendacion");

        jLabelMedicamentos.setText("Medicamentos");

        jButtonSiguienteModificar.setText("1");
        jButtonSiguienteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteModificarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabelSalud))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabelSanguineo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGrupo)
                                .addGap(12, 12, 12)))
                        .addComponent(jComboBoxGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRH)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelDiagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMedicamentos)
                .addGap(108, 108, 108)
                .addComponent(jLabelRecomendaciones)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButtonVolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSiguienteModificar)
                        .addGap(120, 120, 120)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalud)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSanguineo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRH)
                            .addComponent(jComboBoxRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRecomendaciones)
                    .addComponent(jLabelMedicamentos)
                    .addComponent(jLabelDiagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiguienteModificar)
                    .addComponent(jButtonVolver))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteModificarActionPerformed
        cambiarModificarSeguir();
    }//GEN-LAST:event_jButtonSiguienteModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        cambiarVolver();
    }//GEN-LAST:event_jButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSiguienteModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxGrupoSanguineo;
    private javax.swing.JComboBox<String> jComboBoxRH;
    private javax.swing.JLabel jLabelConvenio;
    private javax.swing.JLabel jLabelDiagnostico;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelMedicamentos;
    private javax.swing.JLabel jLabelRH;
    private javax.swing.JLabel jLabelRecomendaciones;
    private javax.swing.JLabel jLabelSalud;
    private javax.swing.JLabel jLabelSanguineo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnostico;
    private javax.swing.JTextArea jTextAreaMedicamentos;
    private javax.swing.JTextArea jTextAreaRecomendaciones;
    private javax.swing.JTextField jTextFieldConvenio;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonSiguienteModificar.setText("Siguiente");
        }if(cambio==2){
            jButtonSiguienteModificar.setText("Modificar");
        }
    }
    private void CargarComboBox() {
        String GrupoSanguineo[] = { "","A","B","AB","O"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(GrupoSanguineo);
        jComboBoxGrupoSanguineo.setModel(model);
        String RH[] = { "","-","+"};
        final DefaultComboBoxModel model1 = new DefaultComboBoxModel(RH);
        jComboBoxRH.setModel(model1);
        jTextAreaDiagnostico.setLineWrap(true);
        jTextAreaDiagnostico.setWrapStyleWord(true);
        jTextAreaMedicamentos.setLineWrap(true);
        jTextAreaMedicamentos.setWrapStyleWord(true);
        jTextAreaRecomendaciones.setLineWrap(true);
        jTextAreaRecomendaciones.setWrapStyleWord(true);
    }
    private void cambiarModificarSeguir() {
        if(panel==1){
            if(VerificarDatos()){
                String afiliacionSalud = jTextFieldConvenio.getText();
                String grupoSanguineo=(String) jComboBoxGrupoSanguineo.getSelectedItem();
                String rH=(String) jComboBoxRH.getSelectedItem();
                String diagnostico = jTextAreaDiagnostico.getText();
                String medicamentos = jTextAreaMedicamentos.getText();
                String recomendaciones = jTextAreaRecomendaciones.getText();
                if(principal.CrearSalud(afiliacionSalud,grupoSanguineo,rH,diagnostico,medicamentos,recomendaciones,cedula)){
                    principal.mostrarPanelPreFamilia();
                    principal.CambioPreFamilia(1);
                    principal.CambioCedulaPreFamilia(cedula);
                    principal.CargarFamiliaSalud(cedula);
                }else{
                    JOptionPane.showMessageDialog(null, "DATOS ERRONEOS");
                }
            }    
        }if(panel==2){
            
        }
    }
    void CambiarCedual(long cedula) {
        this.cedula = cedula;
    }
    private void cambiarVolver() {
        if(panel==1){
            principal.mostrarPanelPerfilAcademico();
            principal.CambioPerfilAcademico(1);
            principal.CambioCedulaPerfilAcademico(cedula);
            principal.CargarPerfilAcademico(cedula);
        }if(panel==2){
            principal.mostrarPanelModificar();
        }
    }
    private boolean VerificarDatos() {
        if(jTextFieldConvenio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA AFILIACION DE SALUD");
            return false;
        }else if(((String) jComboBoxGrupoSanguineo.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE GRUPO SANGUINEO");
            return false;
        }else if(((String) jComboBoxRH.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE RH");
            return false;
        }
        return true;
    }
    void CargarSalud(String[] DatosSalud) {
        jTextFieldConvenio.setText(DatosSalud[0]);
        jComboBoxGrupoSanguineo.setSelectedIndex(TipoGrupoSanguineo(DatosSalud[1]));
        jComboBoxRH.setSelectedIndex(TipoRH(DatosSalud[2]));;
        jTextAreaDiagnostico.setText(DatosSalud[3]);
        jTextAreaMedicamentos.setText(DatosSalud[4]);
        jTextAreaRecomendaciones.setText(DatosSalud[5]);
        principal.EliminarSalud(cedula);
    }
    private int TipoGrupoSanguineo(String grupoSanguineo) {
        if(grupoSanguineo.equals("A")){
            return 1;
        }else if(grupoSanguineo.equals("B")){
            return 2;
        }else if(grupoSanguineo.equals("AB")){
            return 3;
        }else if(grupoSanguineo.equals("O")){
            return 4;
        }
        return 0;
    }
    private int TipoRH(String RH) {
        if(RH.equals("-")){
            return 1;
        }else if(RH.equals("+")){
            return 2;
        }
        return 0;
    }
}
