/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Principal;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class Talleres extends javax.swing.JPanel {
    private Principal principal;
    int panel=0;
    /**
     * Creates new form Talleres
     */
    public Talleres(Principal principal) {
        this.principal=principal;
        initComponents();
        CargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCupos = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonCrearModificar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TALLERES");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelEstado.setText("Estado");

        jComboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEstadoItemStateChanged(evt);
            }
        });

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabelDescripcion.setText("Descripcion");

        jLabel2.setText("Cupos");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonCrearModificar.setText("1");
        jButtonCrearModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelDescripcion)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCupos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrearModificar)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonCrearModificar))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearModificarActionPerformed
        CambiarCrearModificar();
    }//GEN-LAST:event_jButtonCrearModificarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Volver();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        EventoComboBox();
    }//GEN-LAST:event_jLabel1MouseExited

    private void jComboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEstadoItemStateChanged
        EventoComboBox();
    }//GEN-LAST:event_jComboBoxEstadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldCupos;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
    public void CambiarPanel(int cambio){
        panel=cambio;
        if(cambio==1){
            jButtonCrearModificar.setText("Crear");
        }if(cambio==2){
            jButtonCrearModificar.setText("Modificar");
        }
    }
    private void CargarComboBox() {
        String estado[] = { "", "Activo", "Inactivo"};
        final DefaultComboBoxModel model = new DefaultComboBoxModel(estado);
        jComboBoxEstado.setModel(model);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setWrapStyleWord(true);
    }

    private void CambiarCrearModificar() {
        if(panel==1){
            if(VerificarDatos()){
                if(TallerExiste()){
                    if(VerificarNumero()){
                        String nombre = jTextFieldNombre.getText();
                        boolean estado=true;
                        if(((String) jComboBoxEstado.getSelectedItem()).equals("Activo")){
                            estado=true;
                        }else{
                            estado=false;
                        }
                        int cupos = -1;
                        if(!(jTextFieldCupos.getText().equals(""))){
                            cupos = Integer.parseInt(jTextFieldCupos.getText());
                        }
                        String descripcion = jTextAreaDescripcion.getText();
                        if(principal.CrearTaller(nombre,estado,cupos,descripcion)){
                            principal.mostrarPanelPreTalleres();
                            principal.CargarTalleres();
                        }else{
                            JOptionPane.showMessageDialog(this, "Datos erroenos");
                        }
                    }    
                }else{
                    JOptionPane.showMessageDialog(this, "TALLER YA EXISTENTE");
                }
                
            }   
        }if(panel==2){
            
        }
    }
    private boolean TallerExiste() {
        return principal.TallerExiste(jTextFieldNombre.getText());
    }
    private void Volver() {
        principal.mostrarPanelPreTalleres();
        principal.CargarTalleres();
    }
    private boolean VerificarDatos() {
        if(jTextFieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE EL NOMBRE");
            return false;
        }else if(((String) jComboBoxEstado.getSelectedItem()).equals("")){
            JOptionPane.showMessageDialog(null, "SELECCIONE EL ESTADO");
            return false;
        }else if(jTextAreaDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE LA DESCRIPCION");
            return false;
        } 
        return true;
    }

    private boolean VerificarNumero() {
        if(!(jTextFieldCupos.getText().equals(""))){
            if(esNumero(jTextFieldCupos.getText())){
                JOptionPane.showMessageDialog(null, "CUPOS ERRONEOS");
                return false;
            }
            
        }
        if(((String) jComboBoxEstado.getSelectedItem()).equals("Activo")){
            if(jTextFieldCupos.getText().equals("")){
                JOptionPane.showMessageDialog(null, "CUPOS ERRONEOS");
                return false;
            }
        }
        return true;    
    }
    private static boolean esNumero(String cadena) {
        try {
            Long.parseLong(cadena);
            return false;
        } catch (NumberFormatException nfe) {
            return true;
        }
    }

    private void EventoComboBox() {
        if(((String) jComboBoxEstado.getSelectedItem()).equals("Inactivo")){
            jTextFieldCupos.setEnabled(false);
            jTextFieldCupos.setText("");
       }else{
            jTextFieldCupos.setEnabled(true);
        }
    }
}
